---
title: "SARIMA"
author: "Dihan09"
date: "`r Sys.Date()`"
output: html_document
---
```{r Library}
library(readxl)
library(TSA)
library(tseries)
library(starma)
library(MASS)
library(forecast)
library(TTR)
library(graphics)
library(astsa)
library(car)
library(portes)
library(lmtest)
library(ggplot2)
library(gridExtra)
library(patchwork)
library(scales)
```
```{r LoadData}
Data = read_excel("C:/Users/HP/OneDrive/Documents/Semester 6/MDW/Data Laporan SARIMA UAS.xlsx")

Data.ts = ts(Data$ProduksiPadi,
             frequency = 12,
             start = c(2018, 1),
             end = c(2025, 12))
DataTrain = window(Data.ts, end = c(2024, 12))
DataTest  = window(Data.ts, start = c(2025, 1))
plot(Data.ts, main = "Produksi Padi Indonesia (Juta Ton) Tahun 2018-2025", type = "l", xlab = "Tahun", ylab = "Produksi Padi")

plot(
  Data.ts,
  main = "Produksi Padi Indonesia (Juta Ton) Tahun 2018-2025",
  type = "o",
  col = "blue",
  pch = 16,
  lwd = 1.5,
  cex = 0.7,
  xlab = "Tahun",
  ylab = "Produksi Padi"
)

points(
  Data.ts,
  col = "red",
  pch = 16,
  cex = 0.7
)
```
```{r StaDes}
summary(Data)
sd(Data.ts)
summary(DataTrain)
summary(DataTest)
```
```{r StatDeskTahun}
library(readxl)
library(dplyr)

Data = read_excel("C:/Users/HP/OneDrive/Documents/Semester 6/MDW/Data Laporan SARIMA UAS.xlsx")

Data.ts = ts(Data$ProduksiPadi,
             frequency = 12,
             start = c(2018, 1),
             end = c(2025, 12))

DataTrain = window(Data.ts, end = c(2024, 12))
DataTest  = window(Data.ts, start = c(2025, 1))

plot(Data.ts,
     main = "Produksi Padi Indonesia Tahun 2018-2025",
     type = "o",
     col = "blue",
     pch = 16,
     lwd = 1.5,
     cex = 0.7,
     xlab = "Tahun",
     ylab = "Produksi Padi")
points(
  Data.ts,
  col = "red",
  pch = 16,
  cex = 0.7
)


# Membuat data bulan dan tahun
Data_StatDes = data.frame(
  Tahun = rep(2018:2025, each = 12),
  Bulan = rep(month.abb, times = 8),
  ProduksiPadi = as.numeric(Data.ts)
)

# Statistik deskriptif setiap tahun
StatDes_Tahunan = Data_StatDes %>%
  group_by(Tahun) %>%
  summarise(
    Minimum = min(ProduksiPadi, na.rm = TRUE),
    Kuartil_1 = quantile(ProduksiPadi, 0.25, na.rm = TRUE),
    Median = median(ProduksiPadi, na.rm = TRUE),
    Mean = mean(ProduksiPadi, na.rm = TRUE),
    Kuartil_3 = quantile(ProduksiPadi, 0.75, na.rm = TRUE),
    Maksimum = max(ProduksiPadi, na.rm = TRUE),
    Standar_Deviasi = sd(ProduksiPadi, na.rm = TRUE)
  )

StatDes_Tahunan
```
```{r {Plot}
plot(DataTrain,
     main = "Plot Data Train Produksi Padi Indonesia",
     type = "l",
     col = "blue",
     lwd = 2,
       pch = 16,
  cex = 0.7,
     xlab = "Tahun",
     ylab = "Produksi Padi")
points(
  DataTrain,
  col = "red",
  pch = 16,
  cex = 0.7
)

rata = mean(DataTrain)
abline(h = rata, col = "red", lwd = 2)
```

```{r IdentifikasiPolaMusiman}
monthplot(DataTrain,
          main = "Plot Musiman Produksi Padi",
          col = "red",
          xlab = "Bulan",
          ylab = "Produksi Padi")

seasonplot(DataTrain,
           year.labels = TRUE,
           col = rainbow(7),
           main = "Seasonal Plot Produksi Padi",
           xlab = "Bulan",
           ylab = "Produksi Padi")

boxplot(DataTrain ~ cycle(DataTrain),
        main = "Boxplot Produksi Padi per Bulan",
        xlab = "Bulan",
        ylab = "Produksi Padi",
        col = "red")

```

```{r PenentuanPeriodeMusiman}
frequency(DataTrain)
s = 12
s
```
```{r UjiStasioneritas=Varians}
u1 = boxcox(lm(DataTrain ~ 1))
lambda = u1$x[which.max(u1$y)]
lambda

DataVar = DataTrain^lambda

plot(DataVar,
     main = "Data Setelah Transformasi Box-Cox",
     type = "l",
     col = "blue",
     lwd = 2,
     xlab = "Tahun",
     ylab = "Data Transformasi")

abline(h = mean(DataVar), col = "red", lwd = 2)

u2 = boxcox(lm(DataVar ~ 1))
lambda2 = u2$x[which.max(u2$y)]
lambda2
```
```{r UjiStasioneritas=Rataan}
adf.test(DataVar)
```
```{r DiffNon-MusimanOrde1}
Data_diff = diff(DataVar, differences = 1)

plot(Data_diff,
     main = "Data Train Differencing Non-Musiman",
     type = "l",
     col = "black",
     lwd = 2,
     xlab = "Waktu",
     ylab = "Differencing")
points(
  Data_diff,
  col = "red",
  pch = 16,
  cex = 0.7
)

abline(h = mean(Data_diff), col = "red", lwd = 2)

adf.test(Data_diff)
```
```{r DiffMusimanSeaonal}
Data_diff_seasonal = diff(Data_diff, lag = 12, differences = 1)

plot(Data_diff_seasonal,
     main = "Data Train Differencing Musiman",
     type = "l",
     col = "black",
     lwd = 2,
     xlab = "Waktu",
     ylab = "Differencing Seasonal")
points(
  Data_diff_seasonal,
  col = "red",
  pch = 16,
  cex = 0.7
)

abline(h = mean(Data_diff_seasonal), col = "red", lwd = 2)

adf.test(Data_diff_seasonal)
```
```{r IdentifikasiParameterModelSARIMA}
Acf(Data_diff,
    lag.max = 36,
    main = "Plot ACF",
    xlab = "Lag",
    ylab = "ACF")

Acf(Data_diff_seasonal,
    lag.max = 36,
    main = "Plot ACF (Seasonal)",
    xlab = "Lag",
    ylab = "ACF")

Pacf(Data_diff,
     lag.max = 36,
     main = "Plot PACF (Non Seasonal)",
     xlab = "Lag",
     ylab = "PACF")

Pacf(Data_diff_seasonal,
     lag.max = 36,
     main = "Plot PACF",
     xlab = "Lag",
     ylab = "PACF")

Acf(Data_diff_seasonal, lag.max = 36, plot = FALSE)
Pacf(Data_diff_seasonal, lag.max = 36, plot = FALSE)
```
```{r EstimasiParameterSARIMA}
# Seasonal (1,1,1)
model1  = Arima(DataTrain, order=c(1,1,1),
                seasonal=list(order=c(1,1,1),period=12))

model2  = Arima(DataTrain, order=c(2,1,1),
                seasonal=list(order=c(1,1,1),period=12))

model3  = Arima(DataTrain, order=c(1,1,2),
                seasonal=list(order=c(1,1,1),period=12))

model4  = Arima(DataTrain, order=c(2,1,2),
                seasonal=list(order=c(1,1,1),period=12))

model5  = Arima(DataTrain, order=c(3,1,1),
                seasonal=list(order=c(1,1,1),period=12))

# Seasonal (1,1,0)
model6  = Arima(DataTrain, order=c(1,1,1),
                seasonal=list(order=c(1,1,0),period=12))

model7  = Arima(DataTrain, order=c(2,1,1),
                seasonal=list(order=c(1,1,0),period=12))

model8  = Arima(DataTrain, order=c(1,1,2),
                seasonal=list(order=c(1,1,0),period=12))

model9  = Arima(DataTrain, order=c(2,1,2),
                seasonal=list(order=c(1,1,0),period=12))

model10 = Arima(DataTrain, order=c(3,1,1),
                seasonal=list(order=c(1,1,0),period=12))

# Seasonal (0,1,1)
model11 = Arima(DataTrain, order=c(1,1,1),
                seasonal=list(order=c(0,1,1),period=12))

model12 = Arima(DataTrain, order=c(2,1,1),
                seasonal=list(order=c(0,1,1),period=12))

model13 = Arima(DataTrain, order=c(1,1,2),
                seasonal=list(order=c(0,1,1),period=12))

model14 = Arima(DataTrain, order=c(2,1,2),
                seasonal=list(order=c(0,1,1),period=12))

model15 = Arima(DataTrain, order=c(3,1,1),
                seasonal=list(order=c(0,1,1),period=12))

summary(model1);  coeftest(model1)
summary(model2);  coeftest(model2)
summary(model3);  coeftest(model3)
summary(model4);  coeftest(model4)
summary(model5);  coeftest(model5)

summary(model6);  coeftest(model6)
summary(model7);  coeftest(model7)
summary(model8);  coeftest(model8)
summary(model9);  coeftest(model9)
summary(model10); coeftest(model10)

summary(model11); coeftest(model11)
summary(model12); coeftest(model12)
summary(model13); coeftest(model13)
summary(model14); coeftest(model14)
summary(model15); coeftest(model15)
```
```{r EvaluasiModel}
list_model = list(
model1,model2,model3,model4,model5,
model6,model7,model8,model9,model10,
model11,model12,model13,model14,model15
)

nama_model = c(
"SARIMA(1,1,1)(1,1,1)[12]",
"SARIMA(2,1,1)(1,1,1)[12]",
"SARIMA(1,1,2)(1,1,1)[12]",
"SARIMA(2,1,2)(1,1,1)[12]",
"SARIMA(3,1,1)(1,1,1)[12]",

"SARIMA(1,1,1)(1,1,0)[12]",
"SARIMA(2,1,1)(1,1,0)[12]",
"SARIMA(1,1,2)(1,1,0)[12]",
"SARIMA(2,1,2)(1,1,0)[12]",
"SARIMA(3,1,1)(1,1,0)[12]",

"SARIMA(1,1,1)(0,1,1)[12]",
"SARIMA(2,1,1)(0,1,1)[12]",
"SARIMA(1,1,2)(0,1,1)[12]",
"SARIMA(2,1,2)(0,1,1)[12]",
"SARIMA(3,1,1)(0,1,1)[12]"
)

EvaluasiModel = data.frame(
Model = nama_model,
AIC = sapply(list_model,AIC),
BIC = sapply(list_model,BIC)
)

EvaluasiModel = EvaluasiModel[order(EvaluasiModel$AIC),]

print(EvaluasiModel)
```
```{r DiagnostikResidual}
model = list(
  model1, model2, model3, model4, model5,
  model6, model7, model8, model9, model10,
  model11, model12, model13, model14, model15
)

diagnostik = data.frame(
  Model = nama_model,
  AIC = NA,
  BIC = NA,
  Ljung_Box_pvalue = NA,
  KS_Normalitas_pvalue = NA,
  RMSE = NA,
  MAE = NA,
  MAPE = NA
)

for(i in 1:length(model)) {
  
  res = residuals(model[[i]])
  
  pred = forecast(model[[i]], h = length(DataTest))
  
  acc = accuracy(pred, DataTest)
  
  diagnostik$AIC[i] = AIC(model[[i]])
  diagnostik$BIC[i] = BIC(model[[i]])
  diagnostik$Ljung_Box_pvalue[i] =
    Box.test(res, lag = 12, type = "Ljung-Box")$p.value
  
  diagnostik$KS_Normalitas_pvalue[i] =
    ks.test(res, "pnorm", mean(res), sd(res))$p.value
  
  diagnostik$RMSE[i] = acc[1, "RMSE"]
  diagnostik$MAE[i]  = acc[1, "MAE"]
  diagnostik$MAPE[i] = acc[1, "MAPE"]
}

diagnostik[,c(1, 4, 5, 8)]
```
```{r WhiteNoise}
diagnostik_lolos = diagnostik[
  diagnostik$Ljung_Box_pvalue > 0.05,
]

diagnostik_lolos[,c(1,8)]
```
```{r ModelTerbaik}
model_terbaik_index =
  which.min(diagnostik_lolos$MAPE)

model_terbaik =
  diagnostik_lolos[model_terbaik_index, ]

model_terbaik
```
```{r ParameterModelTerbaik}
index_model_terbaik =
  match(model_terbaik$Model, nama_model)

best_model =
  model[[index_model_terbaik]]

summary(best_model)
coeftest(best_model)
```
```{r DiagnostikResidualModelTerbaik}
res_best = residuals(best_model)

Acf(res_best,
    lag.max = 36,
    main = paste("ACF Residual", model_terbaik$Model))

Box.test(res_best,
         lag = 12,
         type = "Ljung-Box")

ks.test(res_best,
        "pnorm",
        mean(res_best),
        sd(res_best))

qqnorm(res_best,
       main = paste("QQ Plot Residual", model_terbaik$Model))
qqline(res_best, col = "red")

hist(res_best,
     main = paste("Histogram Residual", model_terbaik$Model),
     xlab = "Residual",
     col = "lightgray",
     border = "white")

checkresiduals(best_model)
```
```{r PlotAktualPrediksiModel}
Prediksi_best = forecast(best_model,
                         h = length(DataTest))

DataFitted = ts(
  fitted(best_model),
  start = start(DataTrain),
  frequency = frequency(DataTrain)
)

DataPrediksi = ts(
  Prediksi_best$mean,
  start = start(DataTest),
  frequency = frequency(DataTest)
)

# tambah margin kanan
par(
  mar = c(5,5,4,8),
  xpd = TRUE
)

plot(
  Data.ts,
  col = "black",
  lwd = 2,
  main = paste(
    "Aktual vs Prediksi",
    model_terbaik$Model
  ),
  xlab = "Waktu",
  ylab = "Produksi Padi"
)

lines(
  DataFitted,
  col = "blue",
  lwd = 2
)

lines(
  DataPrediksi,
  col = "red",
  lwd = 2
)

abline(
  v = time(DataTest)[1],
  col = "gray",
  lty = 2,
  lwd = 2
)

legend(
  "topright",
  inset = c(-0.22, 0),
  legend = c(
    "Aktual",
    "Estimasi",
    "Prediksi"
  ),
  col = c(
    "black",
    "blue",
    "red"
  ),
  lwd = 2,
  bty = "n",
  cex = 1.1
)

par(xpd = FALSE)
```


```{r PlotPrediksi2026Aktual}
# ============================================================
# Plot Aktual + Prediksi Tahun 2026
# Tanpa interval dan tanpa garis pembatas
# ============================================================

model_final =
Arima(
Data.ts,
order = arimaorder(best_model)[1:3],
seasonal = list(
order = arimaorder(best_model)[4:6],
period = 12
)
)

# Prediksi 12 bulan tahun 2026
Prediksi2026 =
forecast(
model_final,
h = 12
)

DataPrediksi2026 =
ts(
Prediksi2026$mean,
start = c(2026,1),
frequency = 12
)

# Tabel hasil prediksi
TabelPrediksi2026 =
data.frame(
Bulan = month.name,
Tahun = 2026,
Prediksi =
round(
as.numeric(
Prediksi2026$mean
),
0
)
)

print(TabelPrediksi2026)

# ============================================================
# PLOT
# ============================================================

par(
mar=c(5,5,4,8),
xpd=TRUE
)

plot(
Data.ts,

xlim=c(2018,2027),

ylim=c(
min(
c(
Data.ts,
Prediksi2026$mean
)
),

max(
c(
Data.ts,
Prediksi2026$mean
)
)
),

main=
paste(
"Produksi Padi Aktual dan Prediksi Tahun 2026\n",
model_terbaik$Model
),

xlab="Waktu",
ylab="Produksi Padi"
)

# Garis prediksi
lines(
DataPrediksi2026,
col="red",
lwd=3
)

# Legend di luar
legend(
"topright",

inset=c(-0.20,0),

legend=c(
"Aktual",
"Prediksi 2026"
),

lwd=c(
2,
3
),

bty="n"
)

par(
xpd=FALSE
)


print(TabelPrediksi2026)
```
```{r PerbandinganAktualPrediksi96Periode}
# ============================================================
# PLOT AKTUAL + PREDIKSI 2026 (FINAL)
# Legend di luar + tanpa garis rata-rata
# ============================================================

png(
filename = "Plot_Prediksi_Produksi_Padi_2026_HD.png",
width = 4200,
height = 2400,
res = 350
)

par(
mar = c(5,5,4,8),
xpd = TRUE
)

plot(
Data.ts,

type = "l",

col = "#0057D9",
lwd = 2.5,

main =
paste(
"Plot Aktual dan Prediksi Produksi Padi Indonesia\n",
model_terbaik$Model
),

xlab = "Tahun",
ylab = "Produksi Padi",

xlim = c(2018, 2027),

ylim =
range(
c(
Data.ts,
DataPrediksi2026
),
na.rm = TRUE
)
)

# ====================================================
# DATA AKTUAL
# ====================================================

points(
Data.ts,

pch = 16,

col = "#E63946",

cex = 0.8
)

# ====================================================
# DATA PREDIKSI 2026
# ====================================================

lines(
DataPrediksi2026,

col = "#6A0DAD",
lwd = 3
)

points(
DataPrediksi2026,

pch = 17,

col = "#6A0DAD",

cex = 1
)

# ====================================================
# LEGEND DI LUAR
# ====================================================

legend(
"topright",

inset = c(
-0.34,
0
),

legend = c(
"Aktual",
"Titik Aktual",
"Prediksi 2026",
"Titik Prediksi"
),

col = c(
"#0057D9",
"#E63946",
"#6A0DAD",
"#6A0DAD"
),

lwd = c(
2.5,
NA,
3,
NA
),

pch = c(
NA,
16,
NA,
17
),

pt.cex = c(
NA,
0.8,
NA,
1
),

bty = "n",

cex = 1
)

par(
xpd = FALSE
)

dev.off()

# ============================================================
# TAMPILKAN DI RSTUDIO
# ============================================================

par(
mar = c(5,5,4,8),
xpd = TRUE
)

plot(
Data.ts,

type="l",

col="#0057D9",

lwd=2.5,

main=
paste(
"Plot Aktual dan Prediksi Produksi Padi Indonesia\n",
model_terbaik$Model
),

xlab="Tahun",

ylab="Produksi Padi",

xlim=c(2018,2027),

ylim=
range(
c(
Data.ts,
DataPrediksi2026
),
na.rm=TRUE
)
)

points(
Data.ts,
col="#E63946",
pch=16,
cex=0.8
)

lines(
DataPrediksi2026,
col="#6A0DAD",
lwd=3
)

points(
DataPrediksi2026,
col="#6A0DAD",
pch=17,
cex=1
)

legend(
"topright",

inset=c(-0.34,0),

legend=c(
"Aktual",
"Titik Aktual",
"Prediksi 2026",
"Titik Prediksi"
),

col=c(
"#0057D9",
"#E63946",
"#6A0DAD",
"#6A0DAD"
),

lwd=c(
2.5,
NA,
3,
NA
),

pch=c(
NA,
16,
NA,
17
),

bty="n",

cex=1
)

par(
xpd=FALSE
)
```








